name: environment
channels:
  - conda-forge
dependencies:
  - python=3.13  # 3.14 does not work with torch.compile() currently
  - pip
  - cairo
  - cairosvg
  - pip:
      - matplotlib==3.10.8
      - numpy==2.4.0
      - pandas==2.3.3
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - tensorboard==2.20.0
      - torch==2.9.1
      - stockfish==4.0.5
      - ipykernel
      - chess==1.11.2
      - torchaudio==2.9.1
      - git-filter-repo
      - setuptools==80.0.0
