name: environment
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
  - pip:
      - matplotlib==3.10.8
      - numpy==2.4.0
      - pandas==2.3.3
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - tensorboard==2.20.0
      - torch==2.9.1
